service: ws-state

frameworkVersion: "2"
variablesResolutionMode: 20210326

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev

resources:
  Resources:
    WsState:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: my_library_ws_state_state_${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: connection-id
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: connection-id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        GlobalSecondaryIndexes:
          - IndexName: UserIdIndex
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
            Projection:
              ProjectionType: "ALL"
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
        StreamSpecification:
          StreamViewType: KEYS_ONLY
  Outputs:
    WsStateArnId:
      Value:
        Fn::GetAtt:
          - WsState
          - StreamArn
      Export:
        Name: Ws-State-Dynamo-Table-${self:provider.stage}
