service: sync-similar-books
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  environment:
    stage: ${self:provider.stage}
    STAGE: ${self:provider.stage}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - lambda:InvokeFunction
          Resource: "arn:aws:lambda:us-east-1:*:function:process-book-cover*"
        - Effect: "Allow"
          Action:
            - "secretsmanager:GetSecretValue"
          Resource: "arn:aws:secretsmanager:us-east-1:*"
        - Effect: "Allow"
          Action:
            - "s3:*"
          Resource: ["arn:aws:s3:::my-library-cover-upload-staging/*", "arn:aws:s3:::my-library-cover-uploads/*"]
        - Effect: Allow
          Action:
            - "execute-api:ManageConnections"
          Resource:
            - "arn:aws:execute-api:*:*:**/@connections/*"

functions:
  sync:
    timeout: 500
    handler: build/index.handler
    # events:
    #   - schedule: rate(1 minute)
